### ISSUE TITLE
Is it possible to have each line wait for user input before advancing?

### ISSUE THREAD

**Issue by foldedpaper** [bladecoder/blade-ink-template#1]
Thank you for the very helpful library, it has been a huge benefit in getting Ink to work with libgdx projects. I have a question about the story-advancing behavior. Currently, each line of a story advances after a set amount of time (default is 0.95f as set in `TextPanel`). 

But I am wondering how to implement waiting for each line to advance on user input. For example, line1 displays, then waits for user's mouse click, then line2 displays, and so on.

I attempted to hack in a solution by modifying the `StoryListener` implemented in `StoryScreen` to not advance at the end of each line, but instead to have the declared `inputProcessor` pass `next()` to the `StoryManager` on mouse click. This made any choices presented by the `ChoicesUI` unclickable. 

So then I tried listening for mouse click, but only passing `next()` when the `storyManager.hasChoices()` is `false`. This works for advancing the text lines on mouse click, but seems to get stuck before displaying choices.

In any case, I quickly ran to the end of my very beginner understanding of the inner workings of the package. So I came here to see if I'm missing something obvious--is there a setting that allows advance-on-input, rather than auto-advance of each line?

**Comment by bladecoder** [comment]
This feature is available in the engine. In the 'Game props' tab set the 'auto hide texts' property to false.

**Comment by foldedpaper** [comment]
Aha, just as I was starting to fear: I was making things FAR too complicated. Thanks for the quick response and for pointing me to the right place.

**Comment by bladecoder** [comment]
Well, I answer from my phone thinking that the issue was for the bladecoder-adventure-engine project.

I reopen it.

You can add this code to the `TextPanel` constructor:

```
addListener(new ClickListener() {
			public void clicked (InputEvent event, float x, float y) {
                              if(!sm.hasChoices())
				    ui.getWorld().getCurrentScene().getTextManager().next();
			}
		});
```

Hope this helps.
